# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory inside the container
WORKDIR /app
ENV GIT_PYTHON_GIT_EXECUTABLE=/usr/bin/git
# Copy the requirements file into the container at /app
COPY requirements.txt .
# Copy the entire directory into the container
#COPY ..\dataset_working /app/dataset_working
# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code into the container
COPY . .

CMD mlflow server --host 0.0.0.0 --port 5000 & python mlflow_code.py
