# Switch to a Python base image for the Flask application
FROM python:3.9

# Set the working directory for the Flask application
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install Python dependencies for the Flask application
RUN pip install --no-cache-dir -r requirements.txt

# Expose port 8000 for Flask app
EXPOSE 8000

# Set environment variables
ENV PYTHONUNBUFFERED=1

# Specify the command to run the Flask application with Uvicorn
CMD ["uvicorn", "api_Code:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
